version: '3'
services:
  control:
    privileged: true
    build:
      context: ./env
      dockerfile: Dockerfile-control
    container_name: control
    hostname: control
    links:
      - lb
      - web1
      - web2
    volumes:
      - ./ansible:/home/ansible/ansible
    networks:
      ex-ansible-net:
        ipv4_address: 172.66.0.2
    extra_hosts:
      - 'web2:172.66.0.5'
      - 'web1:172.66.0.4'
      - 'lb:172.66.0.3'

  lb:
    privileged: true
    build:
      context: ./env
      dockerfile: Dockerfile
    container_name: lb
    hostname: lb
    links:
      - web1
      - web2
    ports:
      - "8001:80"
    networks:
      ex-ansible-net:
        ipv4_address: 172.66.0.3
    extra_hosts:
      - 'web2:172.66.0.5'
      - 'web1:172.66.0.4'
      - 'control:172.66.0.2'

  web1:
    privileged: true
    build:
      context: ./env
      dockerfile: Dockerfile
    container_name: web1
    hostname: web1
    ports:
      - "8081:80"
    networks:
      ex-ansible-net:
        ipv4_address: 172.66.0.4
    extra_hosts:
      - 'web2:172.66.0.5'
      - 'lb:172.66.0.3'
      - 'control:172.66.0.2'

  web2:
    privileged: true
    build:
      context: ./env
      dockerfile: Dockerfile
    container_name: web2
    hostname: web2
    ports:
      - "8082:80"
    networks:
      ex-ansible-net:
        ipv4_address: 172.66.0.5
    extra_hosts:
      - 'web1:172.66.0.4'
      - 'lb:172.66.0.3'
      - 'control:172.66.0.2'

networks:
  ex-ansible-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.66.0.0/24
